# Generated by Django 5.1.4 on 2024-12-28 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Incident_to_Respondent',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('respondent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surakshak.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('T', 'Tresspassing'), ('F', 'Fire'), ('S', 'Suspicious')], max_length=1)),
                ('severity', models.IntegerField()),
                ('camera_id', models.IntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surakshak.respondent')),
            ],
        ),
    ]
