# Generated by Django 5.1.4 on 2024-12-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(max_length=100)),
            ],
        ),
    ]
