# Generated by Django 5.1.4 on 2024-12-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0002_cameras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
    ]
