# Generated by Django 5.1.4 on 2024-12-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0003_rename_cameras_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
