# Generated by Django 5.1.4 on 2024-12-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0004_camera_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('T', 'Tresspassing'), ('F', 'Fire'), ('S', 'Suspicious')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.AlterField(
            model_name='incident',
            name='camera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surakshak.cameras'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surakshak.incidents'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='respondent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surakshak.respondents'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surakshak.respondents'),
        ),
        migrations.DeleteModel(
            name='Incident_to_Respondent',
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
