# Generated by Django 5.1.4 on 2024-12-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0005_cameras_incidents_respondents_delete_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('T', 'Tresspassing'), ('F', 'Fire'), ('S', 'Suspicious')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surakshak.incidents_types'),
        ),
        migrations.AlterField(
            model_name='respondents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surakshak.incidents_types'),
        ),
        migrations.DeleteModel(
            name='Incidents',
        ),
    ]
