# Generated by Django 5.1.4 on 2025-01-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0006_incidents_types_alter_incident_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
        migrations.RenameModel(
            old_name='Respondents',
            new_name='Respondent',
        ),
    ]
