# Generated by Django 5.1.4 on 2025-01-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0007_rename_cameras_camera_rename_respondents_respondent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='Cameras',
        ),
        migrations.RenameModel(
            old_name='Respondent',
            new_name='Respondents',
        ),
    ]
