# Generated by Django 5.1.4 on 2025-01-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0008_rename_camera_cameras_rename_respondent_respondents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
        migrations.RenameModel(
            old_name='Respondents',
            new_name='Respondent',
        ),
    ]
