# Generated by Django 5.1.4 on 2025-01-02 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0009_rename_cameras_camera_rename_respondents_respondent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=1, unique=True)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='type',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='camera_id',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='incident_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surakshak.respondent'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surakshak.incidenttype'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='incident_type',
            field=models.ManyToManyField(to='surakshak.incidenttype'),
        ),
        migrations.DeleteModel(
            name='Incidents_types',
        ),
    ]
