# Generated by Django 5.1.4 on 2025-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshak', '0010_incidenttype_remove_respondent_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttype',
            name='type_code',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='incident_type',
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='respondents',
            field=models.ManyToManyField(related_name='incident_types', to='surakshak.respondent'),
        ),
    ]
